(()=>{const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;let smoother=null;if(!reduced&&window.gsap&&window.ScrollTrigger&&window.ScrollSmoother){gsap.registerPlugin(ScrollTrigger,ScrollSmoother);smoother=ScrollSmoother.create({wrapper:'#smooth-wrapper',content:'#smooth-content',smooth:.9,effects:false,normalizeScroll:false})}
function stagger(el){const text=[...el.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join('').trim();if(!text)return;el.setAttribute('aria-label',text);[...el.childNodes].filter(n=>n.nodeType===3).forEach(n=>n.remove());const clip=document.createElement('span');clip.className='stagger-label';clip.setAttribute('aria-hidden','true');[...text].forEach((c,i)=>{const col=document.createElement('span');col.className='stagger-char';col.style.setProperty('--i',i);const stack=document.createElement('span');stack.className='stagger-stack';[c,c].forEach(v=>{const g=document.createElement('span');g.textContent=v===' '?'\u00a0':v;stack.append(g)});col.append(stack);clip.append(col)});el.prepend(clip)}document.querySelectorAll('.stagger').forEach(stagger);
fetch('index.html').then(r=>r.text()).then(t=>{const d=new DOMParser().parseFromString(t,'text/html'),n=d.querySelectorAll('.update').length;if(n)document.querySelectorAll('[data-count]').forEach(el=>el.textContent=n)}).catch(()=>{});
const progress=document.querySelector('.reading-progress span');const setProgress=()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?scrollY/max*100:0)+'%'};addEventListener('scroll',setProgress,{passive:true});setProgress();
const processItems=[...document.querySelectorAll('[data-process]')],meter=document.querySelector('.process-meter span'),status=document.querySelector('[data-process-status]');processItems.forEach((item,index)=>item.querySelector('button').addEventListener('click',()=>{processItems.forEach((x,i)=>x.classList.toggle('active',i===index));meter.style.width=(index+1)*25+'%';status.textContent=String(index+1).padStart(2,'0')+' / '+item.querySelector('h3').textContent}));
document.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{if(window.ScrollTrigger)requestAnimationFrame(()=>ScrollTrigger.refresh())}));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.querySelector(a.hash);if(target&&smoother){e.preventDefault();smoother.scrollTo(target,true,'top 78px')}}));
if(!reduced&&window.gsap&&window.ScrollTrigger){gsap.from('.hero h1 span,.hero h1 em',{yPercent:110,opacity:0,duration:1,stagger:.09,ease:'power3.out'});gsap.from('.hero-description,.hero-aside,.hero-index',{y:30,opacity:0,duration:.8,stagger:.12,delay:.35,ease:'power3.out'});gsap.utils.toArray('.section-head').forEach(h=>{gsap.from(h.children,{y:20,opacity:0,stagger:.08,duration:.65,scrollTrigger:{trigger:h,start:'top 84%',once:true}});gsap.from(h.querySelector('i'),{scaleX:0,duration:1,scrollTrigger:{trigger:h,start:'top 84%',once:true}})});gsap.utils.toArray('.underline').forEach(el=>ScrollTrigger.create({trigger:el,start:'top 82%',once:true,onEnter:()=>el.classList.add('drawn')}));gsap.from('.frictions li',{y:45,opacity:0,stagger:.13,duration:.8,ease:'power3.out',scrollTrigger:{trigger:'.frictions',start:'top 80%',once:true}});gsap.fromTo('.parallax-scene',{backgroundPosition:'center 100%'},{backgroundPosition:'center 0%',ease:'none',scrollTrigger:{trigger:'.parallax-scene',start:'top bottom',end:'bottom top',scrub:true}});gsap.from('.parallax-copy>*',{y:45,opacity:0,stagger:.12,duration:.85,ease:'power3.out',scrollTrigger:{trigger:'.parallax-scene',start:'top 65%',once:true}});gsap.utils.toArray('.hover-row').forEach((row,i)=>gsap.from(row,{x:i%2?-45:45,opacity:0,duration:.8,ease:'power3.out',scrollTrigger:{trigger:row,start:'top 86%',once:true}}));gsap.from('.guide-copy',{x:-55,opacity:0,duration:1,ease:'power3.out',scrollTrigger:{trigger:'.guides',start:'top 72%',once:true}});gsap.from('.guide-visual',{y:80,opacity:0,stagger:.16,duration:1,ease:'power3.out',scrollTrigger:{trigger:'.guides',start:'top 68%',once:true}});gsap.utils.toArray('.guide-visual img').forEach((img,i)=>gsap.to(img,{yPercent:-7,rotation:i?2:-2,ease:'none',scrollTrigger:{trigger:img,start:'top bottom',end:'bottom top',scrub:1}}));processItems.forEach((item,i)=>ScrollTrigger.create({trigger:item,start:'top 58%',end:'bottom 42%',onEnter:()=>item.querySelector('button').click(),onEnterBack:()=>item.querySelector('button').click()}));gsap.utils.toArray('.record-parts article').forEach((item,i)=>{gsap.from(item,{x:-35,opacity:0,duration:.7,scrollTrigger:{trigger:item,start:'top 80%',once:true}});ScrollTrigger.create({trigger:item,start:'top 55%',onEnter:()=>gsap.to('.record-card',{rotationY:(i-1.5)*1.1,y:i*5,duration:.55}),onEnterBack:()=>gsap.to('.record-card',{rotationY:(i-1.5)*1.1,y:i*5,duration:.55})})});gsap.from('.source-list details',{y:35,opacity:0,stagger:.12,duration:.75,scrollTrigger:{trigger:'.source-list',start:'top 80%',once:true}});gsap.to('.continuity h2',{xPercent:-5,ease:'none',scrollTrigger:{trigger:'.continuity',start:'top bottom',end:'bottom top',scrub:1}})}
if(!reduced&&matchMedia('(pointer:fine)').matches){document.querySelectorAll('.hover-row').forEach(row=>row.addEventListener('pointermove',e=>{const r=row.getBoundingClientRect();row.style.setProperty('--mx',(e.clientX-r.left)/r.width*100+'%')}))}
})();
